config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # get 'static_pages/help'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # workaroud
  end
  # root to: 'static_pages#redirect_to_root'
  # get :home, to: 'static_pages#home'
  root to: 'static_pages#home'
  get :sotensai_2024, to: 'static_pages#sotensai_2024'

  scope :hub do
    resources :users
  end
  
  scope :circle_hub do
    root to: 'static_pages#redirect_to_about_circle_root', as: :circle_hub_root
    get :q_and_a, to: 'static_pages#q_and_a'
    get :tech_stack, to: 'static_pages#tech_stack'
    get :wip, to: 'static_pages#wip'
    resources :circles do
      collection do
        get :about
      end
      member do
        resource :circle_admin, only: [] do
          get :index
          get :member_list
          get :member_show
          get :role_index
          get :role_new
          get :role_edit
          get :request_pending
          get :request_index
          get :notification_setting

          get :activity_log
          get :wip
        end

        resources :from_user_requests
      end
    end
  end

  namespace :newshub do
    root to: 'static_pages#about'
    resources :news do
      collection do
      end
    end
  end

  namespace :apihub do
    root to: 'static_pages#wip'
    namespace :api do
      namespace :v1 do
        namespace :system do
          resource :news, only: [:create]
        end

        namespace :circlehub do
        end

        namespace :newshub do
          resources :news, only: [:index, :show] # TODO: add more actions
        end

        namespace :apihub do
        end
      end
    end
  end

  constraints host: Rails.configuration.x.domains.admin_hub do
    resources :site_admin
  end

  constraints host: 'r.nomiss.net' do
    get :c24s, to: 'makeshift_redirect#redirect'
    get :c2024s, to: 'makeshift_redirect#redirect'
  end


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
end

app/controllers/apihub/static_pages_controller.rb
class Apihub::StaticPagesController < StaticPagesController
  def about
  end
end

app/controllers/newshub/static_pages_controller.rb
class Newshub::StaticPagesController < StaticPagesController
  def about
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < HubThemeController
  def home
  end

  def help
  end

  def q_and_a
  end

  def routes
    @routes = Rails.application.routes.routes
  end

  def tech_stack
  end

  def sotensai_2024
  end

  def wip
  end

  def redirect_to_root
    redirect_to home_path
  end

  def redirect_to_about_circle_root
    redirect_to about_circles_path
  end

  protected

  def page_title
    {
      'home' => 'ホーム',
      'help' => 'ヘルプ',
      'q_and_a' => 'よくある質問',
      'wip' => 'WIP',
    }[action_name] || action_name.titleize
  end

  def breadcrumbs
    if ['help', 'q_and_a', 'wip'].include?(action_name)
      [
        { name: "ホーム", url: root_path, },
        { name: page_title, disabled: true },
      ]
    else
      nil
    end
  end
end

app/views/static_pages/help.html.slim
h1 StaticPages#help
p Find me in app/views/static_pages/help.html.slim

app/views/static_pages/hiu_hub.html.slim
h1 StaticPages#hiu_hub

= button_to "新規登録", new_user_registration_path, method: :get, class: "btn btn-primary"
= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger"

h2 サークル概要ページ
= link_to 'サークル概要ページ', circles_path

app/views/static_pages/home.html.slim
/ h1 StaticPages#home
/ p Find me in app/views/static_pages/home.html.slim

/ = button_to "新規登録", new_user_registration_path, method: :get, class: "btn btn-primary"
/ = button_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger"

/ h1 StaticPages#home
/ p Find me in app/views/static_pages/home.html.slim
/ p サークル概要ページ

/ h2 サークル新規作成
/ = link_to 'サークル新規作成', new_circle_path

/ h2 サークル名
/ - @circles.each do |circle|
/   a[href=circle_path(circle)]
/     = circle.name
/   br

main.main
  / section 
  section#hero.hero.section
    .container
      .row.gy-4.justify-content-center.text-center
        .col-lg-9.order-2.order-lg-1.d-flex.flex-column
          .d-flex.pb-4.flex-column.flex-md-row.align-items-center
            .col-6.col-md-4.p-1
              = link_to about_circles_path do
                img.img-fluid[src=asset_path("scaffold-theme/circlehub-900x300.png") alt=""]
            .col-6.col-md-4.p-1
              = link_to newshub_root_path do
                img.img-fluid[src=asset_path("scaffold-theme/newshub-tekitou.png") alt=""]
            .col-6.col-md-4.p-1
              = link_to apihub_root_path do
                img.img-fluid[src=asset_path("scaffold-theme/apihub-tekitou.png") alt=""]
          - hero_title = [ \
            "大学の全てを一つに。", # まともなキャッチコピー \
          ].sample
          h1.pb-2
            - hero_title.split("\n").each do |line|
              = line
              br
          p
            / = hero_desc
            | ポータルの確認、書類の提出、サークルの管理、講義の確認。
            br
            | Hubは大学の情報を一つにまとめるためのアプリケーションです。

          .d-flex.justify-content-center
            = link_to 'ユーザー登録', new_user_registration_path, class: 'btn-get-started'
              / | まずはユーザー登録
            / a.glightbox.btn-watch-video.d-flex.align-items-center[href="https://www.youtube.com/watch?v=Y7f98aduVJ8"]
              i.bi.bi-play-circle
              span
                | Watch Video
  section#about.about.section
    .container.section-title[data-aos="fade-up"]
      h2
        | サービス一覧
      p
        | Hubが提供しているサービスを紹介します。
    .container.pb-5[data-aos="fade-up"]
      .row.gx-0
        .col-lg-6.d-flex.align-items-center[data-aos="zoom-out" data-aos-delay="100"]
          img.img-fluid[src=asset_path("scaffold-theme/circlehub-900x300.png") alt=""]
        .col-lg-6.d-flex.flex-column.justify-content-center[data-aos="fade-up" data-aos-delay="100"]
          .content
            h3
              | 団体・サークルを一元管理
            h2
              | CircleHub
            p
              | CircleHubはサークルの運営を効率化するためのアプリケーションです。サークルの新規作成、部員の管理、書類の提出などを一元管理できます。
            .text-center.text-lg-start
              = link_to about_circles_path, class: 'btn-read-more d-inline-flex align-items-center justify-content-center align-self-center' do
                span
                  | CircleHub紹介ページへ
                i.bi.bi-arrow-right

    .container.pb-5.newshub-color[data-aos="fade-up"]
      .row.gx-0
        .col-lg-6.d-flex.align-items-center[data-aos="zoom-out" data-aos-delay="100"]
          img.img-fluid[src=asset_path("scaffold-theme/newshub-tekitou.png") alt=""]
        .col-lg-6.d-flex.flex-column.justify-content-center[data-aos="fade-up" data-aos-delay="100"]
          .content
            h3
              | ニュースを一元管理
            h2
              | NewsHub
            p
              | NewsHubは大学のニュースを一元管理するためのアプリケーションです。大学のイベント告知、部活動報告、学生の活動報告などを一元管理できます。
            .text-center.text-lg-start
              = link_to newshub_root_path, class: 'btn-read-more d-inline-flex align-items-center justify-content-center align-self-center' do
                span
                  | NewsHub紹介ページへ
                i.bi.bi-arrow-right

    .container.pb-5.apihub-color[data-aos="fade-up"]
      .row.gx-0
        .col-lg-6.d-flex.align-items-center[data-aos="zoom-out" data-aos-delay="100"]
          img.img-fluid[src=asset_path("scaffold-theme/apihub-tekitou.png") alt=""]
        .col-lg-6.d-flex.flex-column.justify-content-center[data-aos="fade-up" data-aos-delay="100"]
          .content
            h3
              | 開発者向けHubサービス
            h2
              | APIHub
            p
              | APIHubはHubサービスを利用するためのAPIを提供するためのアプリケーションです。開発優先度は低めですが、要望があれば開発します。
            .text-center.text-lg-start
              = link_to apihub_root_path, class: 'btn-read-more d-inline-flex align-items-center justify-content-center align-self-center' do
                span
                  | APIHub紹介ページへ
                i.bi.bi-arrow-right
  
  section#call-to-action.call-to-action.section.light-background
    img[src=asset_path("scaffold-theme/cta-bg.jpg") alt=""]
      .container
        .row[data-aos="zoom-in" data-aos-delay="100"]
          .col-xl-9.text-center.text-xl-start
            h3
              | Hub【プレビュー版】を利用してみる
            p
              | Hubサービスは開発中のアプリケーションです。以下のボタンから登録を行い、ご利用ください。
          .col-xl-3.cta-btn-container.text-center
            = link_to 'ユーザー登録', new_user_registration_path, class: 'cta-btn align-middle'

  / section#services.services.section
    .container.section-title[data-aos="fade-up"]
      h2
        | その他のサービス一覧
      p
        | HIUHubではあらゆるデータを一元化するサービス群を制作しています。
    .container
      .row.gy-4
        .col-xl-3.col-md-6.d-flex[data-aos="fade-up" data-aos-delay="100"]
          .w-100.service-item.position-relative
            .icon
              i.bi.bi-people.icon
            h4
              a.stretched-link[href=""]
                | CircleHub
            p
              | 開発中。サークルの管理や申請を一元化し、サークル運営を効率化します。
        .col-xl-3.col-md-6.d-flex[data-aos="fade-up" data-aos-delay="200"]
          .w-100.service-item.position-relative
            .icon
              i.bi.bi-newspaper.icon
            h4
              a.stretched-link[href=""]
                | NewsHub
            p
              | 開発中。サークルの活動報告やイベント告知を一元化します。
        .col-xl-3.col-md-6.d-flex[data-aos="fade-up" data-aos-delay="300"]
          .w-100.service-item.position-relative
            .icon
              i.bi.bi-megaphone.icon
            h4
              a.stretched-link[href=""]
                | APIHub
            p
              | 開発中。各サービスを利用するAPIを提供します。
        .col-xl-3.col-md-6.d-flex[data-aos="fade-up" data-aos-delay="400"]
          .w-100.service-item.position-relative
            .icon
              i.bi.bi-motherboard.icon
            h4
              a.stretched-link[href=""]
                | その他
            p
              | 希望があれば新しいサービスを開発します。ご要望をお寄せください。
  section#developer-invitation.developer-invitation.section.light-background.call-to-action
    .container.section-title[data-aos="fade-up"]
      h2
        | 開発メンバー募集中！
      p
        | 開発メンバーを募集しています。興味のある方はぜひ。
    .container[data-aos="fade-up" data-aos-delay="100"]
      .text-center.text-lg-start.justify-content-center.d-flex
        = link_to '技術スタックはこちら', tech_stack_path, class: 'cta-btn align-self-center'

  = render 'layouts/scaffold_theme/section/contact'
  / section#contact.contact.section
    .container.section-title[data-aos="fade-up"]
      h2
        | お問い合わせ
      p
        | こちらのフォームは現在機能していません。送信しても何も起こらないのでご注意ください。
    .container[data-aos="fade-up" data-aos-delay="100"]
      .row.gy-4
        .col-lg-6
          .row.gy-4
            .col-md-6
              .info-item[data-aos="fade" data-aos-delay="200"]
                i.bi.bi-geo-alt
                h3
                  | Address
                p
                  | A108 Adam Street
                p
                  | New York, NY 535022
            .col-md-6
              .info-item[data-aos="fade" data-aos-delay="300"]
                i.bi.bi-telephone
                h3
                  | Call Us
                p
                  | +1 5589 55488 55
                p
                  | +1 6678 254445 41
            .col-md-6
              .info-item[data-aos="fade" data-aos-delay="400"]
                i.bi.bi-envelope
                h3
                  | Email Us
                p
                  | info@example.com
                p
                  | contact@example.com
            .col-md-6
              .info-item[data-aos="fade" data-aos-delay="500"]
                i.bi.bi-clock
                h3
                  | Open Hours
                p
                  | Monday - Friday
                p
                  | 9:00AM - 05:00PM
        .col-lg-6
          form.php-email-form[action="forms/contact.php" method="post" data-aos="fade-up" data-aos-delay="200"]
            .row.gy-4
              .col-md-6
                input.form-control[type="text" name="name" placeholder="Your Name" required=""]
              .col-md-6
                input.form-control[type="email" name="email" placeholder="Your Email" required=""]
              .col-12
                input.form-control[type="text" name="subject" placeholder="Subject" required=""]
              .col-12
                textarea.form-control[name="message" rows="6" placeholder="Message" required=""]
              .col-12.text-center
                .loading
                  | Loading
                .error-message
                .sent-message
                  | Your message has been sent. Thank you!
                button[type="submit"]
                  | Send Message

app/views/static_pages/q_and_a.html.slim
main.main
  = render "layouts/scaffold_theme/section/qa", \
      title: "一般的な質問", \
      description: "以下は、よくある質問です。ご不明な点があれば、お気軽にお問い合わせください。", \
      qa_list: [ \
        { question: "これは北海道情報大学の公式サイトですか？", answer: "いいえ、Computer Operating Clubの部長が個人で作成したものです。非公式なサイトであることに注意してください", active: true }, \
        { question: "CircleHubを利用するにはどうすればいいですか？", answer: "現在はまだリリース出来る状態ではないためご利用できません。希望する方はリリースが完了時に連絡いたします。学籍番号`2112097`の学内メールアドレス宛にその旨を連絡ください。", }, \
        { question: "この機能がほしい！/ここにバグがありました！", answer: "学籍番号`2112097`の学内メールアドレス宛に連絡をください。希望通りの対応が出来ない可能性もありますが、ご了承ください。", }, \
      ]

  = render "layouts/scaffold_theme/section/qa", \
    title: "CircleHubについて", \
    description: "", \
    qa_list: [ \
      { question: "全ての団体が掲載されていますか？", answer: "いいえ、CircleHubに登録されている団体のみです。", }, \
      { question: "どうすればここに掲載が出来ますか？", answer: "CircleHubにてユーザー登録を行い、団体の作成をしてください。" }, \
    ]

app/views/static_pages/routes.html.slim
h1 StaticPages#home
p Find me in app/views/static_pages/routes.html.slim

- @routes.each do |route|
  = link_to route.name, route_path(route)
  br

app/views/static_pages/sotensai_2024.html.slim
main.main 
  section
    .container.section-title[data-aos="fade-up"]
      h2
        | 蒼天祭
      p
        | 2024年度の蒼天祭についての情報を掲載しています。
    .container[data-aos="fade-up" data-aos-delay="100"]
      .row.gy-4.justify-content-center
        .col-lg-10
          .row.gy-4
            .col-12
              h3
                | 蒼天祭2024 メインポスター
            .col-12
              img.img_fluid.col-12[src=asset_path("scaffold-theme/sotensai2024-main.png") alt=""]
            .col-12
              h3
                | 情報一元化アプリの紹介
            .col-12
              p
                | Hubという学内の情報一元化Webアプリを制作しています。ゼミ室11にて展示をしますので興味のある方は是非お越しください。
            .col-12.text-center
                = link_to "Hubについて詳しく", root_path, class: "btn btn-primary btn-block"
            .col-12
              h3
                | 開発者コミュニティの紹介
            .col-12
              p 
                | Hubの開発に興味がある方は、以下の開発者コミュニティに参加してください。
            .col-12
              .row.justify-content-center
                .col-4
                  img.img-fluid[src=asset_path("scaffold-theme/QR_cocdiscord.png") alt=""]
            .col-12.text-center
              = link_to "開発者コミュニティに参加", root_path, class: "btn btn-primary btn-block"
            .col-12
              h3
                | React+Next.jsによるWebアプリケーション開発
            .col-12
              p 
                | ゼミ室11にて説明しております。

app/views/static_pages/tech_stack.html.slim
main.main
  section#team.team.section.light-background
    .container.section-title[data-aos="fade-up"]
      h2
        | 開発メンバー
      p
        | バックエンドにはRuby on Rails 7、フロントエンドにはBootstrap 4と5を利用したテンプレートを使用しています。
    .container
      .row.gy-5.justify-content-center
        - [ \
            { image: "scaffold-theme/team/aaaa777_b_600x600.png", name: "Yuma Sawai / aaaa777", role: "経営情報学部システム情報学科", socials: [ \
              { icon: 'bi-github', url: 'https://github.com/aaaa777' }, \
              # { icon: 'bi-twitter-x', url: 'https://twitter.com/aaaa777' }, \
              # { icon: 'bi-facebook', url: 'https://www.facebook.com/aaaa777' }, \
              # { icon: 'bi-instagram', url: 'https://www.instagram.com/aaaa777' } \
            ]}, \
            # { image: "scaffold-theme/team/noname_h_600x600.png", name: "開発メンバー募集中", role: "必要スキル: Ruby on Rails" }, \
          ].each_with_index do |member, i|
          .col-lg-4.col-md-6[data-aos="fade-up" data-aos-delay=(member[:delay] || (100 + i * 100))]
            .member
              .pic
                img.img-fluid[src=asset_path(member[:image]) alt=""]
              .member-info
                h4
                  = member[:name]
                span
                  = member[:role]
                .social
                  - member[:socials]&.each do |social|
                    a[href=social[:url]]
                      i.bi[class="#{social[:icon]}"]

app/views/static_pages/wip.html.slim
main.main
  section#developer-invitation.developer-invitation.section.light-background.call-to-action
    .container.section-title[data-aos="fade-up"]
      h2
        | Work in Progress
      p
        | このページは現在開発中です。しばらくお待ちください。
    .container[data-aos="fade-up" data-aos-delay="100"]
      .text-center.text-lg-start.justify-content-center.d-flex
        = link_to 'ホームに戻る', root_path, class: 'cta-btn align-self-center'