config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # get 'static_pages/help'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # workaroud
  end
  # root to: 'static_pages#redirect_to_root'
  # get :home, to: 'static_pages#home'
  root to: 'static_pages#home'
  get :sotensai_2024, to: 'static_pages#sotensai_2024'

  scope :hub do
    resources :users
  end
  
  scope :circle_hub do
    root to: 'static_pages#redirect_to_about_circle_root', as: :circle_hub_root
    get :q_and_a, to: 'static_pages#q_and_a'
    get :tech_stack, to: 'static_pages#tech_stack'
    get :wip, to: 'static_pages#wip'
    resources :circles do
      collection do
        get :about
      end
      member do
        resource :circle_admin, only: [] do
          get :index
          get :member_list
          get :member_show
          get :role_index
          get :role_new
          get :role_edit
          get :request_pending
          get :request_index
          get :notification_setting

          get :activity_log
          get :wip
        end

        resources :from_user_requests
      end
    end
  end

  namespace :newshub do
    root to: 'static_pages#about'
    resources :news do
      collection do
      end
    end
  end

  namespace :apihub do
    root to: 'static_pages#wip'
    namespace :api do
      namespace :v1 do
        namespace :system do
          resource :news, only: [:create]
        end

        namespace :circlehub do
        end

        namespace :newshub do
          resources :news, only: [:index, :show] # TODO: add more actions
        end

        namespace :apihub do
        end
      end
    end
  end

  constraints host: Rails.configuration.x.domains.admin_hub do
    resources :site_admin
  end

  constraints host: 'r.nomiss.net' do
    get :c24s, to: 'makeshift_redirect#redirect'
    get :c2024s, to: 'makeshift_redirect#redirect'
  end


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
end

app/models/concerns/requests/in_circlehub.rb
module Requests::InCircle
  
end

app/models/request.rb
class Request < ApplicationRecord
  enum :status, {
    pending: 'pending',
    approved: 'approved',
    rejected: 'rejected',
  }

  belongs_to :circle
  belongs_to :request_type
  belongs_to :applicant, class_name: 'User', optional: true
  belongs_to :approver, class_name: 'User', optional: true
end

app/models/request_type.rb
class RequestType < ApplicationRecord
  enum flow_name: {
    join_circle_provisional_member: 'join_circle_provisional_member',
    join_circle_member: 'join_circle_member',
    leave_circle: 'leave_circle',
  }

  belongs_to :circle
  has_many :requests
  has_many :enabled_request_types

  def from_user_request_type
    FromUserRequestType.find_by(id: id)
  end

  def from_admin_request_type
    FromAdminRequestType.find_by(id: id)
  end
end

app/models/requests/circle_join.rb
class Requests::CircleJoin < Requests

end

app/models/requests/circle_join_provisionally.rb
class Requests::CircleJoinProvisionally < Requests

end

app/models/requests/circle_leave.rb
class Requests::CircleLeave < Requests

end

app/models/requests/request.rb
class AbstractRequest < ApplicationRecord
  enum :status, {
    pending: 'pending',
    approved: 'approved',
    rejected: 'rejected',
  }
  string :note

  belongs_to :circle
  belongs_to :request_type
  belongs_to :applicant, class_name: 'Member'
  belongs_to :approver, class_name: 'Member'
end

app/models/requests/request_type.rb
class RequestType < ApplicationRecord
  string :title
  string :description

  belongs_to :circle
  has_many :abstract_requests
  has_many :enabled_request_types
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController


  def index
    @circle = Circle.find(params[:id])
    @request_types = RequestType.all
  end

  def new
    @circle = Circle.find(params[:id])
    @request = Request.new(request_type: @request_type)
    @request_type = RequestType.find_by(id: params[:request_type_id])
  end

  def show
    @circle = Circle.find(params[:id])
    @request = CircleRequest.find(params[:id])
  end

  def edit
    @circle = Circle.find(params[:id])
    @request = CircleRequest.find(params[:id])
  end

  # Circleの管理者のみor作成者が操作可能

  def create
    @circle = Circle.find(params[:id])
    @request = Request.new(request_params)
    debugger
    if @request.save
      redirect_to root_path, notice: "リクエストを送信しました"
    else
      @request_type = @request.request_type
      flash.now[:alert] = "リクエストの送信に失敗しました"
      render :new, params: { request_type_id: @request.request_type_id }
    end
  end

  def update
    @circle = Circle.find(params[:id])
    @request = CircleRequest.find(params[:id])
  end

  def destroy
    @circle = Circle.find(params[:id])
    @request = CircleRequest.find(params[:id])
  end

  protected

  def request_params
    params.require(:request).permit(:request_type_id, :name, :note).merge(circle: @circle).merge(applicant: current_user).merge(status: "pending")
  end
  
end

app/views/requests/index.html.slim
= render 'layouts/form/form', title: @circle.name, title_link: circles_path, description: "#{@circle.name}が現在受け付けている申請一覧です"
  - @request_types.each do |request_type|
    = link_to request_type.title, new_from_user_request_path(@circle, request_type_id: request_type)
    br

app/views/requests/new.html.slim
= render 'layouts/form/form', title: "#{@circle.name} #{@request_type.title}", title_link: circles_path, description: @request_type.description, back_link: from_user_requests_path(@circle)
  - if @requests_user_has_sent.present?
    #error_explanation[data-turbo-cache="false"]
      h2
        | あなたは既に
          a[href="#"]
            = "#{@requests_user_has_sent.count} 件の申請"
        | を送信しています"
  = form_with model: @user, url: '#', data: { turbo: false } do |f|
    = f.label :first_name
    .input-group.mb-3
      = f.text_field :first_name, class: "form-control", disabled: true
      .input-group-append
        .input-group-text
          span.fas.fa-user
  = form_with model: @request, data: { turbo: false } do |f|
    = f.text_field :request_type_id, value: @request_type.id, type: 'hidden'
    = f.label :note
    .input-group.mb-3
      = f.text_area :note, autofocus: true, autocomplete: "note", class: "form-control", placeholder: "特筆事項があれば記入してください"
      / .input-group-append
      /   .input-group-text
      /     span.fas.fa-envelope
    .row
      .col-12
        = f.submit '申請', class: 'btn btn-primary btn-block'