config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'
  # get 'static_pages/help'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy' # workaroud
  end
  # root to: 'static_pages#redirect_to_root'
  # get :home, to: 'static_pages#home'
  root to: 'static_pages#home'
  get :sotensai_2024, to: 'static_pages#sotensai_2024'

  scope :hub do
    resources :users
  end
  
  scope :circle_hub do
    root to: 'static_pages#redirect_to_about_circle_root', as: :circle_hub_root
    get :q_and_a, to: 'static_pages#q_and_a'
    get :tech_stack, to: 'static_pages#tech_stack'
    get :wip, to: 'static_pages#wip'
    resources :circles do
      collection do
        get :about
      end
      member do
        resource :circle_admin, only: [] do
          get :index
          get :member_list
          get :member_show
          get :role_index
          get :role_new
          get :role_edit
          get :request_pending
          get :request_index
          get :notification_setting

          get :activity_log
          get :wip
        end

        resources :from_user_requests
      end
    end
  end

  namespace :newshub do
    root to: 'static_pages#about'
    resources :news do
      collection do
      end
    end
  end

  namespace :apihub do
    root to: 'static_pages#wip'
    namespace :api do
      namespace :v1 do
        namespace :system do
          resource :news, only: [:create]
        end

        namespace :circlehub do
        end

        namespace :newshub do
          resources :news, only: [:index, :show] # TODO: add more actions
        end

        namespace :apihub do
        end
      end
    end
  end

  constraints host: Rails.configuration.x.domains.admin_hub do
    resources :site_admin
  end

  constraints host: 'r.nomiss.net' do
    get :c24s, to: 'makeshift_redirect#redirect'
    get :c2024s, to: 'makeshift_redirect#redirect'
  end


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
end

app/models/circle.rb
class Circle < ApplicationRecord
  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  has_many :members
  has_many :request_types
  has_many :requests
  has_many :enabled_request_types
end

app/models/circles/circle.rb
class Circle < ApplicationRecord
  string :name
  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  has_many :members
  has_many :request_types
  has_many :abstract_requests
  has_many :enabled_request_types
end

app/models/circles/enabled_request_type.rb
class EnabledRequest < ApplicationRecord
  belongs_to :circle
  belongs_to :request_type
end

app/models/circles/member.rb
class Member < ApplicationRecord
  enum status: {
    pending_to_join: 'pending_to_join',
    canceled_to_join: 'canceled_to_join',
    provisionally_joined: 'provisionally_joined',
    joined: 'joined',
    left: 'left',
    other: 'other'
  }

  belongs_to :user
  belongs_to :circle
  has_many :abstract_request_applicants, class_name: 'AbstractRequest', foreign_key: 'applicant_id'
  has_many :abstract_request_approvers, class_name: 'AbstractRequest', foreign_key: 'approver_id'

  validates :circle_id, presence: true
end

app/controllers/circles_controller.rb
class CirclesController < CircleHubController
  # before_action :load_data

  def about
  end

  def index
    @circles = Circle.all
  end

  def show
    @circle = Circle.find(params[:id])
  end

  def new
    @circle = Circle.new
  end

  def create
    @circle = Circle.new(circle_params)
    if @circle.save
      redirect_to @circle
    else
      render :new
    end
  end

  protected

  def hub_image
    "scaffold-theme/circlehub-900x300.png"
  end

  def page_title
    {
      'index' => '団体一覧',
      'show' => '団体詳細',
      'new' => '団体新規作成',
    }[action_name] || action_name.titleize
  end

  def breadcrumbs
    if ['show', 'new'].include?(action_name)
      [
        { name: "団体一覧", url: circles_path, },
        { name: page_title, disabled: true },
      ]
    # elsif action_name == 'index'
    #   [
    #     { name: "団体一覧", disabled: true },
    #   ]
    else
      nil
    end
  end

  # def load_data
  #   @header_list = header_list
  # end

  # def store_location?
  #   true
  # end

  # def header_list
  #   [
  #     { name: "Home", type: :link, url: request.path == circles_path ? "#hero" : circles_path(id: :hero), },
  #     { name: "About", type: :link, url: request.path == circles_path ? "#about" : circles_path(id: :about), },
  #     { name: "Circles", type: :link, url: circles_path, },
  #     { name: "Dropdown", type: :dropdown, items: [
  #       { name: "Item 1", type: :link, url: "#", },
  #       { name: "Deep Dropdown", type: :dropdown, items: [
  #         { name: "Item 1", type: :link, url: "#", },
  #         { name: "Item 2", type: :link, url: "#", },
  #       ]},
  #     ]},
  #   ]
  # end

  private

  def circle_params
    params.require(:circle).permit(:name)
  end

end

app/views/circles/index.html.slim
= render "layouts/scaffold_theme/section/portfolio", \
  title: "CircleHub掲載団体一覧(サンプル)", \
  description: "全ての公認団体を掲載しているわけではありませんのでご注意ください。", \
  filter_headers: [{ name: "全て", filter: "*", active: true }, { name: "文化部", filter: ".filter-culture" }, { name: "運動部", filter: ".filter-sport" }, { name: "その他", filter: ".filter-other" }], \
  items: [ \
    { image_url: asset_path("scaffold-theme/portfolio/culture.png"), title: "Computer Operating Club", description: "コンピュータ関連のことならなんでもします！", filter: "culture" }, \
    { image_url: asset_path("scaffold-theme/portfolio/sport.png"), title: "部活1", description: "Lorem ipsum, dolor sit amet consectetur", filter: "sport" }, \
    { image_url: asset_path("scaffold-theme/portfolio/culture.png"), title: "その他1", description: "Lorem ipsum, dolor sit amet consectetur", filter: "culture" }, \
    { image_url: asset_path("scaffold-theme/portfolio/sport.png"), title: "部活2", description: "Lorem ipsum, dolor sit amet consectetur", filter: "sport" }, \
    { image_url: asset_path("scaffold-theme/portfolio/culture.png"), title: "サークル2", description: "Lorem ipsum, dolor sit amet consectetur", filter: "culture" }, \
    { image_url: asset_path("scaffold-theme/portfolio/other.png"), title: "学生実行委員会", description: "情報大学の企画・運営をします。", filter: "other" }, \
    { image_url: asset_path("scaffold-theme/portfolio/culture.png"), title: "その他2", description: "Lorem ipsum, dolor sit amet consectetur", filter: "culture" }, \
    { image_url: asset_path("scaffold-theme/portfolio/culture.png"), title: "サークル3", description: "Lorem ipsum, dolor sit amet consectetur", filter: "culture" }, \
    { image_url: asset_path("scaffold-theme/portfolio/sport.png"), title: "部活3", description: "Lorem ipsum, dolor sit amet consectetur", filter: "sport" }, \
  ]

section#call-to-action.call-to-action.section
  / img[src=asset_path("scaffold-theme/cta-bg.jpg") alt=""]
  .container
    .row[data-aos="zoom-in" data-aos-delay="100"]
      .col-xl-9.text-center.text-xl-start
        h3
          | 所属団体がリストにありませんか？
        p
          | もしリストにない場合は、今すぐCircleHubで作成しましょう！
          | 作成は簡単で、すぐに他のユーザーに公開されます。
      .col-xl-3.cta-btn-container.text-center
        a.cta-btn.align-middle[href="#"]
          | 団体を作成する

app/views/circles/new.html.slim
/ = render 'layouts/form/form', title: 'Circle-Hub', title_link: circles_path, description: 'Circle-Hubに団体を作成します。'
/   - if @circle.errors.any?
/     ul
/       - @circle.errors.full_messages.each do |message|
/         li = message
/   = form_with model: @circle, method: :post, url: circles_path do |f|
/     = f.label :name
/     .input-group.mb-3
/       = f.text_field :name, autofocus: true, class: "form-control", placeholder: "団体名"
/       / .input-group-append
/       /   .input-group-text
/       /     span.fas.fa-signature
/     = f.label :description
/     .input-group.mb-3
/       = f.text_area :description, class: "form-control", placeholder: "団体の説明"
/       / .input-group-append
/       /   .input-group-text
/       /     span.fas.fa-envelope
/     .row
/       .col-12
/         = f.submit '団体を作成', class: 'btn btn-primary btn-block'

/ = render 'layouts/scaffold_theme/section/form', title: '新規団体作成', description: '新規団体を作成します。', resource: @circle
= render 'layouts/scaffold_theme/section/contact'
/ section#contact.contact.section
  .container.section-title[data-aos="fade-up"]
    h2
      | 新規団体作成
    p
      | 新規団体を作成します。
  .container[data-aos="fade-up" data-aos-delay="100"]
    .row.gy-4.justify-content-center
      .col-lg-10
        = form_with model: @circle, method: :post, url: circles_path do |f|
          .row.gy-4
            .col-12
              = f.label :name
              = f.text_field :name, class: "form-control", placeholder: "例）Computer Operating Club", required: true
            .col-12
              = f.label :description
              = f.text_area :description, class: "form-control", placeholder: "例）技術的な交流をするサークルです！"
            .col-12.text-center
              = f.submit '新規作成', class: 'btn btn-primary btn-block'
        / form.php-email-form[action="forms/contact.php" method="post" data-aos="fade-up" data-aos-delay="200"]
        /   .row.gy-4
        /     .col-12
        /       label
        /         | 団体名
        /       input.form-control[type="text" name="name" placeholder="Computer Operating Club" required=""]
        /     .col-12
        /       label
        /         | 団体の説明（任意）
        /       textarea.form-control[name="message" rows="6" placeholder="技術的な交流をするサークルです！" required=""]
        /     .col-12.text-center
        /       .loading
        /         | Loading
        /       .error-message
        /       .sent-message
        /         | Your message has been sent. Thank you!
        /       button[type="submit"]
        /         | Send Message

app/views/circles/show.html.slim
h1 白紙のページ
p サークル概要ページ

h2 サークル名
p
  = @circle.name

h2 ダッシュボード
p
  = link_to 'ダッシュボード', circle_admin_path(@circle)

h2 CircleRequest 
p
  = link_to 'CircleRequest', from_user_requests_path(@circle)